# My First Workflow

name: workflow1
on: 
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "hello from Ana."
      - name: step2
        run: echo "Good morning."
      - name: step3
        run: cat /etc/os-release
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Save data
        run: echo 'Completed'

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Try testing
        run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
